# Generated by Django 5.2.5 on 2025-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixonauta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amonia', models.IntegerField()),
                ('temperatura', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
