# Generated by Django 5.2.6 on 2025-09-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixonauta', '0002_parametro_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraAmonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
