# Generated by Django 5.2.6 on 2025-09-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peixonauta', '0003_leituraamonia_delete_parametro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
