# Generated by Django 5.2.5 on 2025-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixonauta', '0005_leituraph_leituratemperatura_leituraturbidez'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
